variables:
   ARM_PASS: $(adminPass)

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'quickstarts/microsoft.web/webapp-linux-managed-mysql/'
    Contents: '**'
    TargetFolder: '

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Cloudtravellers (b69c2a11-bd8a-4349-b9d9-1c55bd839199)'
    subscriptionId: 'b69c2a11-bd8a-4349-b9d9-1c55bd839199'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'CICDRG-PIPE'
    location: 'East US 2'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/azuredeploy.parameters.json'
    overrideParameters: '-siteName $(siteName) -administratorLogin $(adminUser) -administratorLoginPassword $(ARM_PASS)'
    deploymentMode: 'Incremental'